export interface IProfileResponseModel {
    address: string,
    city: string,
    countryId: number,
    createdOn: Date,
    email: string,
    firstName: string,
    houseNo: string,
    lastName: string,
    phoneNumber: string,
    profilePicture: string,
    stateId: number,
    userId: string,
    zipCode: string,
}
